# Generated by Django 2.2.2 on 2019-07-05 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conslutantinfo',
            name='position',
            field=models.CharField(default='CEO', max_length=50),
            preserve_default=False,
        ),
    ]
