# Generated by Django 2.2.2 on 2019-07-10 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_conslutantinfo_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='question',
            field=models.TextField(default='testing', max_length=100),
            preserve_default=False,
        ),
    ]
