# Generated by Django 2.2.2 on 2019-06-28 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190628_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='send',
            field=models.BooleanField(),
        ),
    ]
