# Generated by Django 2.2.2 on 2019-07-12 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190710_0338'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='yourneed',
            field=models.CharField(default='ds', max_length=30),
            preserve_default=False,
        ),
    ]
